{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dataiku.name" . }}
  labels:
    {{- include "dataiku.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.front.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "dataiku.name" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
          - path: {{ .Values.ingress.api.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "dataiku.name" . }}-api
                port:
                  number: {{ .Values.api.service.port }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecret }}
  {{- end }}
{{- end }}