frontend:
  replicas: 2
  image:
    repository: muraduiurie/dataiku-front
    tag: 3c0d387
    pullPolicy: IfNotPresent
  containerPort: 80
  env: {}
  service:
    port: 80
  resources: {}

api:
  replicas: 2
  image:
    repository: muraduiurie/dataiku-api
    tag: 3c0d387
    pullPolicy: IfNotPresent
  containerPort: 5000
  env: {}
  service:
    port: 80
    monitoringPort: 8000
  resources: {}

ingress:
  enabled: true
  host: dataiku.promoldova.org
  api:
    path: /api
  front:
    path: /
  pathType: Prefix
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
  tls: true
  tlsSecret: dataiku-tls