apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dataiku
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:muraduiurie/dataiku-assessment.git
    targetRevision: main
    path: charts/dataiku
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dataiku
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true