name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL || 'docker.io' }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Set Front Docker image tag
        id: meta
        run: |
          IMAGE_NAME=${{ secrets.REGISTRY_USERNAME }}/dataiku-front
          TAG=${GITHUB_SHA::7}
          echo "image=${IMAGE_NAME}:${TAG}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          cd frontend && \
          docker build -t ${{ steps.meta.outputs.image }} .

      - name: Push Docker image
        run: |
          docker push ${{ steps.meta.outputs.image }}

      - name: Set API Docker image tag
        id: meta
        run: |
          IMAGE_NAME=${{ secrets.REGISTRY_USERNAME }}/dataiku-api
          TAG=${GITHUB_SHA::7}
          echo "image=${IMAGE_NAME}:${TAG}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          cd api && \
          docker build -t ${{ steps.meta.outputs.image }} .

      - name: Push Docker image
        run: |
          docker push ${{ steps.meta.outputs.image }}
